on: { push: { branches: [ gha ] } }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm i
      - run: |
          node --version
          npm --version
          npm ls
      - run: node trees.js
      - run: node subprojects.js
      - run: node root-group.js
